name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build main.cpp
      run: g++ -o myapp $GITHUB_WORKSPACE/src/main.cpp -lstdc++

    - name: Generate Hex File
      run: objcopy -O ihex myapp myapp.hex

    - name: Upload Hex File
      uses: actions/upload-artifact@v2
      with:
        name: myapp-hex
        path: myapp.hex
