name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Move to source directory
      run: cd C:/Users/nvduo/TEST_DTTT/test_DTTT/src

    - name: Compile Code and Generate Hex File
      run: g++ -o myapp main.cpp -lstdc++ && objcopy -O ihex myapp myapp.hex
