name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compile Code and Generate Binary File
      run: |
        g++ -o myapp ./src/main.cpp -lstdc++
        objcopy -O binary myapp myapp.bin
